# Entry Executor Agent Profile
id: "entry_executor"
name: "Entry Executor"
description: "Executes trade entries and manages order placement"
version: "1.0.0"
type: "execution"

capabilities:
  - name: "submit_order"
    description: "Submits a trade order with risk parameters"
    parameters:
      symbol:
        type: "string"
        description: "Symbol to trade"
        required: true
      direction:
        type: "string"
        description: "Trade direction (buy/sell)"
        required: true
      entry_price:
        type: "number"
        description: "Entry price"
        required: true
      stop_loss:
        type: "number"
        description: "Stop loss price"
        required: true
      take_profit:
        type: "number"
        description: "Take profit price"
        required: true
      position_size:
        type: "number"
        description: "Position size"
        required: true
    output_schema:
      type: "object"
      properties:
        order_id:
          type: "string"
          description: "Unique order identifier"
        submitted:
          type: "boolean"
          description: "Whether the order was submitted"

  - name: "cancel_order"
    description: "Cancels an existing order"
    parameters:
      order_id:
        type: "string"
        description: "Identifier of the order"
        required: true
    output_schema:
      type: "object"
      properties:
        cancelled:
          type: "boolean"
          description: "Whether the order was cancelled"

  - name: "adjust_order"
    description: "Adjusts stop loss or take profit of an order"
    parameters:
      order_id:
        type: "string"
        description: "Identifier of the order"
        required: true
      stop_loss:
        type: "number"
        description: "New stop loss price"
        required: false
      take_profit:
        type: "number"
        description: "New take profit price"
        required: false
    output_schema:
      type: "object"
      properties:
        updated:
          type: "boolean"
          description: "Whether the order was updated"

triggers:
  - name: "precision_entry"
    type: "system"
    priority: 90
    condition: "event.type == 'entry_signal'"

  - name: "order_update_request"
    type: "request"
    priority: 80
    condition: "true"

memory_access:
  - namespace: "execution.orders"
    tier: "L2_vector"
    access_type: "read_write"
    ttl_seconds: 604800

token_budget: 800
timeout_seconds: 30
max_consecutive_errors: 3
auto_recovery: true
dependencies: ["risk_manager"]

config:
  default_sl_buffer: 0.0
  default_tp_buffer: 0.0
  max_orders_per_day: 10
