
# NCOS Phoenix-Session Master Configuration
system:
  name: "NCOS Phoenix-Session"
  version: "21.7"
  environment: "production"
  debug: false

# Core settings
core:
  tick_processing:
    buffer_size: 10000
    batch_size: 100
    processing_interval: 0.1

  session_management:
    max_concurrent_sessions: 1
    session_timeout: 86400
    auto_save_interval: 300

# Engine configurations
engines:
  market_structure:
    enabled: true
    lookback_period: 100
    min_structure_distance: 10
    sensitivity: 0.7

  liquidity:
    enabled: true
    liquidity_sensitivity: 0.7
    min_pool_size: 100000
    sweep_detection: true

  volatility:
    enabled: true
    lookback_short: 20
    lookback_long: 100
    regime_threshold: 1.5

  wyckoff:
    enabled: true
    phase_detection: true
    volume_analysis: true

  predictive:
    enabled: true
    ml_models:
      - lstm
      - random_forest
      - xgboost

# Risk management
risk:
  max_position_size: 0.1
  max_daily_loss: 0.02
  max_drawdown: 0.1
  risk_per_trade: 0.01

# API settings
api:
  host: "0.0.0.0"
  port: 8000
  cors_enabled: true
  rate_limiting:
    enabled: true
    requests_per_minute: 60
