version: 21.7.0
agents:
  CoreSystemAgent:
    profile_path: agents/coresystemagent_profile.yaml
    enabled: true
    priority: 1
  MarketDataCaptain:
    profile_path: agents/marketdatacaptain_profile.yaml
    enabled: true
    priority: 1
  PortfolioManager:
    profile_path: agents/portfoliomanager_profile.yaml
    enabled: true
    priority: 1
  SignalProcessor:
    profile_path: agents/signalprocessor_profile.yaml
    enabled: true
    priority: 1
  VoiceCommandAgent:
    profile_path: agents/voicecommandagent_profile.yaml
    enabled: true
    priority: 1
  RiskManager:
    profile_path: agents/riskmanager_profile.yaml
    enabled: true
    priority: 1
