
agents:
  CoreSystemAgent:
    module: "core_system_agent"
    class: "CoreSystemAgent"
    description: "Core system orchestration and lifecycle management"

  VectorMemoryBoot:
    module: "vector_memory_boot"
    class: "VectorMemoryBoot"
    description: "Vector memory initialization and management"

  ParquetIngestor:
    module: "parquet_ingestor"
    class: "ParquetIngestor"
    description: "Parquet file ingestion and processing"

  MarketDataCaptain:
    module: "market_data_captain"
    class: "MarketDataCaptain"
    description: "Market data ingestion and real-time feed management"

  TechnicalAnalyst:
    module: "technical_analyst"
    class: "TechnicalAnalyst"
    description: "Technical analysis and indicator calculation"

  SMCRouter:
    module: "smc_router"
    class: "SMCRouter"
    description: "Smart message routing and load balancing"

  MAZ2Executor:
    module: "maz2_executor"
    class: "MAZ2Executor"
    description: "MAZ2 strategy execution engine"

  TMCExecutor:
    module: "tmc_executor"
    class: "TMCExecutor"
    description: "TMC strategy execution engine"

  RiskGuardian:
    module: "risk_guardian"
    class: "RiskGuardian"
    description: "Risk management and position monitoring"

  PortfolioManager:
    module: "portfolio_manager"
    class: "PortfolioManager"
    description: "Portfolio optimization and allocation management"

  BroadcastRelay:
    module: "broadcast_relay"
    class: "BroadcastRelay"
    description: "Message broadcasting and inter-agent communication"

  ReportGenerator:
    module: "report_generator"
    class: "ReportGenerator"
    description: "Report generation and data visualization"

  SessionStateManager:
    module: "session_state_manager"
    class: "SessionStateManager"
    description: "Session state persistence and recovery"
  market_manipulation_agent:
    module: "ncos_market_manipulation_agent"
    class: "MarketManipulationAgent"
    config_file: "config/xauusd_manipulation_config.yaml"
    enabled: true
  risk_monitor_agent:
    module: "ncos_risk_monitor_agent"
    class: "RiskMonitorAgent"
    config_file: "config/xauusd_manipulation_config.yaml"
    config_section: "risk_monitor_config"
    enabled: true
  compliance_agent:
    module: "ncos_compliance_agent"
    class: "ComplianceAgent"
    enabled: true
  liquidity_sniper:
    module: "liquidity_sniper"
    class: "LiquiditySniperAgent"
    enabled: true
  entry_executor_smc:
    module: "entry_executor_smc"
    class: "EntryExecutorSMCAgent"
    enabled: true
strategy_agents:
  micro_wyckoff_event:
    class: MicroWyckoffEventAgent
    config_file: config/strategies/micro_wyckoff_event.yaml
    dependencies:
    - master_orchestrator
    - risk_guardian
    enabled: true
    max_positions: 1
    module: micro_wyckoff_event
    priority: 10
    risk_per_trade: 0.01
    risk_profile: precision
    timeframes:
    - tick
    - M1
    triggers:
    - tick_event_scored
    - micro_wyckoff_signal
    type: tick_analysis
  orderflow_anomaly:
    class: OrderflowAnomalyAgent
    config_file: config/strategies/orderflow_anomaly.yaml
    dependencies:
    - master_orchestrator
    - liquidity_sniper
    enabled: true
    max_positions: 1
    module: orderflow_anomaly
    priority: 11
    risk_per_trade: 0.015
    risk_profile: defensive
    timeframes:
    - M1
    - M5
    triggers:
    - orderflow_anomaly_detected
    - volume_spike
    type: orderflow_analysis
  protection_reentry:
    class: ProtectionReentryAgent
    config_file: config/strategies/protection_reentry.yaml
    dependencies:
    - risk_guardian
    - session_state_manager
    enabled: true
    max_positions: 3
    module: protection_reentry
    priority: 12
    risk_per_trade: 0.01
    risk_profile: protective
    timeframes:
    - M1
    - M5
    triggers:
    - stop_loss_hit
    - reentry_opportunity
    type: risk_management
  session_sweep_reversal:
    class: SessionSweepReversalAgent
    config_file: config/strategies/session_sweep_reversal.yaml
    dependencies:
    - master_orchestrator
    - entry_executor_smc
    enabled: true
    max_positions: 2
    module: session_sweep_reversal
    priority: 9
    risk_per_trade: 0.02
    risk_profile: moderate
    timeframes:
    - M5
    - M1
    triggers:
    - session_open
    - sweep_reversal_signal
    type: session_trading
  smc_liquidity_trap:
    class: SMCLiquidityTrapAgent
    config_file: config/strategies/smc_liquidity_trap.yaml
    dependencies:
    - master_orchestrator
    - liquidity_sniper
    - risk_guardian
    enabled: true
    max_positions: 2
    module: smc_liquidity_trap
    priority: 7
    risk_per_trade: 0.025
    risk_profile: aggressive
    timeframes:
    - M1
    - M5
    triggers:
    - liquidity_trap_detected
    - engineered_liquidity_signal
    type: smc_execution
  wyckoff_phase_cycle:
    class: WyckoffPhaseCycleAgent
    config_file: config/strategies/wyckoff_phase_cycle.yaml
    dependencies:
    - master_orchestrator
    - session_state_manager
    enabled: true
    max_positions: 1
    module: wyckoff_phase_cycle
    priority: 8
    risk_per_trade: 0.015
    risk_profile: conservative
    timeframes:
    - H1
    - M15
    - M5
    triggers:
    - phase_transition_detected
    - accumulation_signal
    type: wyckoff_analysis
  divergence_strategy_agent:
    class: DivergenceStrategyAgent
    module: ncos_divergence_strategy_agent
    enabled: true
    config:
      account_balance: 100000
      risk_conviction_score: 4
      risk_reward_ratio: 1.5
      max_history_size: 50
      risk_engine_config:
        sl_blend_logic: atr_priority
        min_lot_step: 0.01
        max_lot_size: 20.0
        max_risk_percent: 1.0
        vol_adjustment_explosive: 0.75
      atr_config:
        period: 14
        multiplier: 2.0
