
agents:
  CoreSystemAgent:
    module: "core_system_agent"
    class: "CoreSystemAgent"
    description: "Core system orchestration and lifecycle management"

  VectorMemoryBoot:
    module: "vector_memory_boot"
    class: "VectorMemoryBoot"
    description: "Vector memory initialization and management"

  ParquetIngestor:
    module: "parquet_ingestor"
    class: "ParquetIngestor"
    description: "Parquet file ingestion and processing"

  MarketDataCaptain:
    module: "market_data_captain"
    class: "MarketDataCaptain"
    description: "Market data ingestion and real-time feed management"

  TechnicalAnalyst:
    module: "technical_analyst"
    class: "TechnicalAnalyst"
    description: "Technical analysis and indicator calculation"

  SMCRouter:
    module: "smc_router"
    class: "SMCRouter"
    description: "Smart message routing and load balancing"

  MAZ2Executor:
    module: "maz2_executor"
    class: "MAZ2Executor"
    description: "MAZ2 strategy execution engine"

  TMCExecutor:
    module: "tmc_executor"
    class: "TMCExecutor"
    description: "TMC strategy execution engine"

  RiskGuardian:
    module: "risk_guardian"
    class: "RiskGuardian"
    description: "Risk management and position monitoring"

  PortfolioManager:
    module: "portfolio_manager"
    class: "PortfolioManager"
    description: "Portfolio optimization and allocation management"

  BroadcastRelay:
    module: "broadcast_relay"
    class: "BroadcastRelay"
    description: "Message broadcasting and inter-agent communication"

  ReportGenerator:
    module: "report_generator"
    class: "ReportGenerator"
    description: "Report generation and data visualization"

  SessionStateManager:
    module: "session_state_manager"
    class: "SessionStateManager"
    description: "Session state persistence and recovery"
