_metadata:
  source: ncOS_v21.7-main/config/general_config.yaml
  category: engines
  created: '2025-06-21T16:03:32.623343'
  keys_count: 2
vector_processor:
  settings: { }
vectormemoryboot_config:
  settings: { }
