ncos_market_bias_system:
  version: 21.7.1
  description: Complete market bias tracking, charting, and alerting system integrated
    with NCOS Phoenix Mesh
  created: '2025-06-20T00:16:44.751361'
  core_agents:
    market_data_ingestor:
      id: market_data_ingestor_v21
      type: ingestion
      sources:
      - csv
      - yaml
      - vector_bundle
      - realtime_api
      supported_symbols:
      - XAUUSD
      - SPY
      - DXY
      - GBPJPY
      - EURUSD
      - BTCUSD
      - ES
      - NQ
      memory_namespace: market_data_intraday
      embedding_model: text-embedding-3-small
      schedule: '*/1 * * * *'
      output:
      - vector_memory
      - enriched_csv
      - session_manifest.yaml
      integration:
        ncos_core: true
        vector_engine: enhanced_vector_engine
        data_processor: csv_processor
      status: active
    chart_renderer:
      id: chart_renderer_v21
      type: visualization
      input:
      - vector_memory
      - enriched_csv
      - bias_vector.json
      chart_types:
      - line
      - candlestick
      - filled_area
      - heatmap
      - bias_overlay
      style:
        background: black
        grid: white
        fill: green
        line: lime
        bias_positive: '#00ff00'
        bias_negative: '#ff0000'
        bias_neutral: '#ffff00'
      triggers:
      - on_session_update
      - on_manual_request
      - on_bias_change
      output:
      - chart_image.png
      - chart_image.svg
      - interactive_html
      features:
        bias_overlay: true
        smc_levels: true
        liquidity_zones: true
      status: active
    market_bias_monitor:
      id: market_bias_monitor_v21
      type: macro
      input:
      - vector_memory
      - enriched_csv
      - smc_analysis
      - liquidity_data
      memory_namespace: bias_insights
      embedding_model: text-embedding-3-small
      methods:
      - correlation_analysis
      - trend_classification
      - volatility_clustering
      - smc_pattern_detection
      - liquidity_flow_analysis
      bias_vector_schema:
        symbol: string
        timestamp: iso8601
        trend: upward|downward|neutral
        volatility_spike: boolean
        bias_score: float[-1,1]
        confidence: low|medium|high
        smc_context:
          structure: string
          liquidity_direction: string
          manipulation_detected: boolean
      triggers:
      - on_chart_update
      - on_volatility_event
      - on_session_checkpoint
      - on_smc_signal
      output:
      - bias_vector.json
      - bias_summary.md
      - bias_history.jsonl
      downstream_triggers:
      - chart_renderer
      - event_alert_agent
      - session_flow_tracker
      status: active
    event_alert_agent:
      id: event_alert_agent_v21
      type: alerting
      input:
      - vector_memory
      - event_log.csv
      - bias_vector.json
      memory_namespace: event_signals
      triggers:
      - choch_detected
      - sweep_detected
      - spread_spike
      - custom_pattern
      - bias_change
      - smc_signal
      actions:
      - send_telegram_alert
      - send_webhook
      - log_event
      - update_dashboard
      alert_templates:
        bias_bullish: "\U0001F7E2 BULLISH BIAS: {{symbol}} @ {{price}} | Score: {{bias_score}}\
          \ | Confidence: {{confidence}}"
        bias_bearish: "\U0001F534 BEARISH BIAS: {{symbol}} @ {{price}} | Score: {{bias_score}}\
          \ | Confidence: {{confidence}}"
        bias_neutral: "\U0001F7E1 NEUTRAL BIAS: {{symbol}} @ {{price}} | Consolidation\
          \ detected"
        choch: "\U0001F4C9 CHoCH detected on {{symbol}} at {{price}}"
        sweep: "\U0001F501 Sweep event: {{symbol}} @ {{price}}"
        spread: "\u26A0\uFE0F Spread spike: {{symbol}} spread={{spread}}"
        volatility: "\U0001F6A8 VOLATILITY SPIKE: {{symbol}} | Bias: {{trend}} | Action:\
          \ {{action}}"
      config:
        telegram:
          enabled: true
          token: ${TELEGRAM_BOT_TOKEN}
          chat_id: ${TELEGRAM_CHAT_ID}
        webhook:
          enabled: true
          url: ${WEBHOOK_URL}
          headers:
            Authorization: Bearer ${WEBHOOK_TOKEN}
      status: active
    session_flow_tracker:
      id: session_flow_tracker_v21
      type: session_management
      input:
      - session_manifest.yaml
      - event_log.csv
      - bias_history.jsonl
      tracks:
      - session_start
      - session_end
      - event_sequence
      - export_status
      - bias_evolution
      - profit_tracking
      export:
      - session_manifest.yaml
      - session_events.jsonl
      - summary_report.md
      - bias_timeline.html
      session_schema:
        session_id: uuid
        start_time: iso8601
        end_time: iso8601
        symbols:
        - string
        events:
        - event_object
        alerts:
        - alert_object
        chart_files:
        - file_path
        export_status: string
        bias_summary:
          initial_bias: object
          final_bias: object
          bias_changes:
          - change_event
          accuracy: float
      status: active
  ncos_integration:
    enhanced_core_orchestrator:
      register_agents:
      - market_data_ingestor_v21
      - chart_renderer_v21
      - market_bias_monitor_v21
      - event_alert_agent_v21
      - session_flow_tracker_v21
      priority: high
    smc_analysis_engine:
      bias_feed: true
      output_to: market_bias_monitor
    liquidity_analysis_engine:
      bias_feed: true
      output_to: market_bias_monitor
    enhanced_vector_engine:
      namespaces:
      - market_data_intraday
      - bias_insights
      - event_signals
  workflows:
    bias_detection_flow:
      steps:
      - agent: market_data_ingestor
        action: fetch_data
      - agent: smc_analysis_engine
        action: analyze_structure
      - agent: liquidity_analysis_engine
        action: detect_flows
      - agent: market_bias_monitor
        action: calculate_bias
      - agent: chart_renderer
        action: render_with_bias
      - agent: event_alert_agent
        action: send_alerts
      - agent: session_flow_tracker
        action: log_event
      trigger: on_data_update
  deployment:
    docker_compose:
      services:
        bias_system:
          image: ncos:21.7.1-bias
          environment:
          - NCOS_MODE=bias_tracking
          - VECTOR_DB=enabled
          - REALTIME=true
