agent:
  name: PortfolioManager
  version: 21.7.0
  enabled: true
settings:
  max_positions: 10
  risk_per_trade: 0.01
  max_daily_risk: 0.05
  position_sizing_method: fixed_fractional
  rebalance_interval: 3600
  risk_check_interval: 300
