predictive_scorer:
  enabled: true
  factor_weights:
    htf_bias_alignment: 0.20      # Trend alignment importance
    idm_detected_clarity: 0.10    # Pattern clarity weight
    sweep_validation_strength: 0.15
    choch_confirmation_score: 0.15
    poi_validation_score: 0.20    # Key level importance
    tick_density_score: 0.10
    spread_stability_score: 0.10

  grade_thresholds:
    A: 0.85  # Top tier setups
    B: 0.70  # Quality setups
    C: 0.55  # Marginal setups

  # Additional predictive scorer settings
  min_score_to_emit_potential_entry: 0.65
  conflict_detection_settings:
    enabled: true
    min_new_setup_maturity_for_conflict_alert: 0.70
    suggest_review_trade_if_new_setup_maturity_above: 0.80

data_enricher:
  enabled: true
  calculate_tick_density: true
  calculate_spread_stability: true
  calculate_htf_alignment: true
  spread_tracker_config:
    enabled: true
    window_size: 25
    high_vol_baseline: 0.0008
    stability_threshold: 0.3

feature_extractor:
  enabled: true
  use_cached_features: true
  feature_cache_ttl_seconds: 300

journaling:
  enabled: true
  log_all_evaluations: false
  min_maturity_score_to_log: 0.60
  log_format: json
  log_directory: logs/predictive_journal
