agent:
  name: RiskManager
  version: 21.7.0
  enabled: true
settings:
  log_level: WARNING
  alert_threshold: 0.8
  emergency_close_threshold: 0.95
  max_drawdown: 0.2
  daily_loss_limit: 0.06
  correlation_threshold: 0.7
  var_confidence: 0.95
