agent:
  name: SignalProcessor
  version: 21.7.0
  enabled: true
settings:
  min_confidence: 0.7
  signal_types:
  - entry
  - exit
  - adjustment
  cooldown_period: 300
  confirmation_required: true
  queue_size: 100
  processing_threads: 4
