strategy_triggers:
  liquidity_trap_detected:
    actions:
    - analyze_trap_setup
    - validate_risk_parameters
    conditions:
    - smc_signal_strength > 0.7
    - liquidity_pool_identified
    priority: 8
    route_to:
    - smc_liquidity_trap
    - risk_guardian
  orderflow_anomaly_detected:
    actions:
    - analyze_anomaly
    - adjust_risk_parameters
    conditions:
    - volume_anomaly
    - price_action_divergence
    priority: 6
    route_to:
    - orderflow_anomaly
    - risk_guardian
  phase_transition_detected:
    actions:
    - analyze_phase_transition
    - update_market_context
    conditions:
    - wyckoff_phase_change
    - volume_confirmation
    priority: 7
    route_to:
    - wyckoff_phase_cycle
    - session_state_manager
  session_open:
    actions:
    - scan_for_sweeps
    - prepare_reversal_setups
    conditions:
    - session_start_time
    - volatility_threshold_met
    priority: 9
    route_to:
    - session_sweep_reversal
    - master_orchestrator
  stop_loss_hit:
    actions:
    - evaluate_reentry
    - update_risk_profile
    conditions:
    - position_closed
    - reentry_criteria_met
    priority: 5
    route_to:
    - protection_reentry
    - risk_guardian
  tick_event_scored:
    actions:
    - evaluate_tick_event
    - prepare_precision_entry
    conditions:
    - tick_score > threshold
    - micro_structure_valid
    priority: 10
    route_to:
    - micro_wyckoff_event
    - entry_executor_smc
strategy_triggers:
  liquidity_trap_detected:
    actions:
    - analyze_trap_setup
    - validate_risk_parameters
    conditions:
    - smc_signal_strength > 0.7
    - liquidity_pool_identified
    priority: 8
    route_to:
    - smc_liquidity_trap
    - risk_guardian
  orderflow_anomaly_detected:
    actions:
    - analyze_anomaly
    - adjust_risk_parameters
    conditions:
    - volume_anomaly
    - price_action_divergence
    priority: 6
    route_to:
    - orderflow_anomaly
    - risk_guardian
  phase_transition_detected:
    actions:
    - analyze_phase_transition
    - update_market_context
    conditions:
    - wyckoff_phase_change
    - volume_confirmation
    priority: 7
    route_to:
    - wyckoff_phase_cycle
    - session_state_manager
  session_open:
    actions:
    - scan_for_sweeps
    - prepare_reversal_setups
    conditions:
    - session_start_time
    - volatility_threshold_met
    priority: 9
    route_to:
    - session_sweep_reversal
    - master_orchestrator
  stop_loss_hit:
    actions:
    - evaluate_reentry
    - update_risk_profile
    conditions:
    - position_closed
    - reentry_criteria_met
    priority: 5
    route_to:
    - protection_reentry
    - risk_guardian
  tick_event_scored:
    actions:
    - evaluate_tick_event
    - prepare_precision_entry
    conditions:
    - tick_score > threshold
    - micro_structure_valid
    priority: 10
    route_to:
    - micro_wyckoff_event
    - entry_executor_smc
