profile_name: CoreSystemAgent
description: Core system orchestration and health monitoring
version: 21.7.0
execution_sequence:
- health_check
- system_monitor
- log_aggregator
code_map:
  health_check: ncos.core.health_check.HealthChecker
  system_monitor: ncos.core.system_monitor.SystemMonitor
  log_aggregator: ncos.core.log_aggregator.LogAggregator
meta_agent:
  agent_id: NCOS_Core_001
  strategy_tags:
  - System
  - Health
  - Monitoring
  llm_contextualization_enabled: false
settings:
  log_level: INFO
  health_check_interval: 60
  max_retries: 3
  startup_delay: 5
  shutdown_timeout: 30
