profile_name: PortfolioManager
description: Portfolio optimization and position management
version: 21.7.0
execution_sequence:
- risk_calculator
- position_sizer
- portfolio_optimizer
code_map:
  risk_calculator: ncos.portfolio.risk_calculator.RiskCalculator
  position_sizer: ncos.portfolio.position_sizer.PositionSizer
  portfolio_optimizer: ncos.portfolio.optimizer.PortfolioOptimizer
meta_agent:
  agent_id: NCOS_Portfolio_001
  strategy_tags:
  - Portfolio
  - Risk
  - Optimization
  llm_contextualization_enabled: true
risk_manager:
  enabled: true
  max_risk_per_trade: 0.01
settings:
  max_positions: 10
  risk_per_trade: 0.01
  max_daily_risk: 0.05
  position_sizing_method: fixed_fractional
  rebalance_interval: 3600
  risk_check_interval: 300
