profile_name: RiskManager
description: Risk management and position monitoring
version: 21.7.0
execution_sequence:
- risk_assessment
- position_monitor
- alert_generator
code_map:
  risk_assessment: ncos.risk.assessment.RiskAssessment
  position_monitor: ncos.risk.monitor.PositionMonitor
  alert_generator: ncos.risk.alerts.AlertGenerator
meta_agent:
  agent_id: NCOS_Risk_001
  strategy_tags:
  - Risk
  - Monitor
  - Alert
  llm_contextualization_enabled: false
settings:
  log_level: WARNING
  alert_threshold: 0.8
  emergency_close_threshold: 0.95
  max_drawdown: 0.2
  daily_loss_limit: 0.06
  correlation_threshold: 0.7
  var_confidence: 0.95
