profile_name: SignalProcessor
description: Trading signal processing and validation
version: 21.7.0
execution_sequence:
- context_analyzer
- liquidity_engine
- structure_validator
- fvg_locator
- confluence_stacker
code_map:
  context_analyzer: ncos.signals.context_analyzer.ContextAnalyzer
  liquidity_engine: ncos.signals.liquidity_engine.LiquidityEngine
  structure_validator: ncos.signals.structure_validator.StructureValidator
  fvg_locator: ncos.signals.fvg_locator.FVGLocator
  confluence_stacker: ncos.signals.confluence_stacker.ConfluenceStacker
meta_agent:
  agent_id: NCOS_Signal_001
  strategy_tags:
  - Signal
  - Analysis
  - Validation
  llm_contextualization_enabled: true
  memory_embedding_strategy: on_signal_zbar_summary
context_analyzer:
  enabled: true
  bias_determination_timeframes:
  - H1
  - H4
liquidity_engine:
  enabled: true
  lookback_period: 100
structure_validator:
  enabled: true
  swing_engine_config:
    swing_n: 1
    break_on_close: true
settings:
  min_confidence: 0.7
  signal_types:
  - entry
  - exit
  - adjustment
  cooldown_period: 300
  confirmation_required: true
  queue_size: 100
  processing_threads: 4
journaling:
  verbosity: detailed
  enable_zbar_format: true
  log_directory: /logs/signals/
