profile_name: VoiceCommandAgent
description: Natural language voice command processing
version: 21.7.0
execution_sequence:
- voice_parser
- command_router
- response_generator
code_map:
  voice_parser: ncos.voice.voice_tag_parser.VoiceTagParser
  command_router: ncos.voice.llm_orchestrator.CommandRouter
  response_generator: ncos.voice.response_generator.ResponseGenerator
meta_agent:
  agent_id: NCOS_Voice_001
  strategy_tags:
  - Voice
  - NLP
  - Interface
  llm_contextualization_enabled: true
settings:
  wake_word: ncos
  language: en-US
  confidence_threshold: 0.7
  max_command_length: 100
  timeout: 5
